# Basic
title: jrshutske.github.io
subtitle: jack
description: welcome to my blog
avatarTitle: jrshutske
avatarDesc: software developer
url: "http://jrshutske.github.io"
modified: 2018-09-20

comment:
    disqus:
social:
    github: jrshutske
    mail: jackshutske@gmail.com

permalink: /:year/:month/:title/

highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# Navigation buttons in the front page.s
nav:
    - {title: blog, description: blog, url: '/#blog'}
    - {title: archive, description: archive, url: '/archive'}
    - {title: tags, description: tags, url: '/tags'}
    - {title: about, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 8
paginate_path: "page/:num/"
